/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsersRouteImport } from './routes/users'
import { Route as TimetablesRouteImport } from './routes/timetables'
import { Route as TeachersRouteImport } from './routes/teachers'
import { Route as StudentsRouteImport } from './routes/students'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RoomsRouteImport } from './routes/rooms'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DepartmentsRouteImport } from './routes/departments'
import { Route as DemoModeRouteImport } from './routes/demo-mode'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as ClassesRouteImport } from './routes/classes'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlanningsPlanningIdRouteImport } from './routes/plannings.$planningId'

const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const TimetablesRoute = TimetablesRouteImport.update({
  id: '/timetables',
  path: '/timetables',
  getParentRoute: () => rootRouteImport,
} as any)
const TeachersRoute = TeachersRouteImport.update({
  id: '/teachers',
  path: '/teachers',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentsRoute = StudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomsRoute = RoomsRouteImport.update({
  id: '/rooms',
  path: '/rooms',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DepartmentsRoute = DepartmentsRouteImport.update({
  id: '/departments',
  path: '/departments',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoModeRoute = DemoModeRouteImport.update({
  id: '/demo-mode',
  path: '/demo-mode',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassesRoute = ClassesRouteImport.update({
  id: '/classes',
  path: '/classes',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanningsPlanningIdRoute = PlanningsPlanningIdRouteImport.update({
  id: '/plannings/$planningId',
  path: '/plannings/$planningId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/classes': typeof ClassesRoute
  '/courses': typeof CoursesRoute
  '/demo-mode': typeof DemoModeRoute
  '/departments': typeof DepartmentsRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/rooms': typeof RoomsRoute
  '/settings': typeof SettingsRoute
  '/students': typeof StudentsRoute
  '/teachers': typeof TeachersRoute
  '/timetables': typeof TimetablesRoute
  '/users': typeof UsersRoute
  '/plannings/$planningId': typeof PlanningsPlanningIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/classes': typeof ClassesRoute
  '/courses': typeof CoursesRoute
  '/demo-mode': typeof DemoModeRoute
  '/departments': typeof DepartmentsRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/rooms': typeof RoomsRoute
  '/settings': typeof SettingsRoute
  '/students': typeof StudentsRoute
  '/teachers': typeof TeachersRoute
  '/timetables': typeof TimetablesRoute
  '/users': typeof UsersRoute
  '/plannings/$planningId': typeof PlanningsPlanningIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/classes': typeof ClassesRoute
  '/courses': typeof CoursesRoute
  '/demo-mode': typeof DemoModeRoute
  '/departments': typeof DepartmentsRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/rooms': typeof RoomsRoute
  '/settings': typeof SettingsRoute
  '/students': typeof StudentsRoute
  '/teachers': typeof TeachersRoute
  '/timetables': typeof TimetablesRoute
  '/users': typeof UsersRoute
  '/plannings/$planningId': typeof PlanningsPlanningIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/classes'
    | '/courses'
    | '/demo-mode'
    | '/departments'
    | '/login'
    | '/profile'
    | '/rooms'
    | '/settings'
    | '/students'
    | '/teachers'
    | '/timetables'
    | '/users'
    | '/plannings/$planningId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/classes'
    | '/courses'
    | '/demo-mode'
    | '/departments'
    | '/login'
    | '/profile'
    | '/rooms'
    | '/settings'
    | '/students'
    | '/teachers'
    | '/timetables'
    | '/users'
    | '/plannings/$planningId'
  id:
    | '__root__'
    | '/'
    | '/classes'
    | '/courses'
    | '/demo-mode'
    | '/departments'
    | '/login'
    | '/profile'
    | '/rooms'
    | '/settings'
    | '/students'
    | '/teachers'
    | '/timetables'
    | '/users'
    | '/plannings/$planningId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClassesRoute: typeof ClassesRoute
  CoursesRoute: typeof CoursesRoute
  DemoModeRoute: typeof DemoModeRoute
  DepartmentsRoute: typeof DepartmentsRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  RoomsRoute: typeof RoomsRoute
  SettingsRoute: typeof SettingsRoute
  StudentsRoute: typeof StudentsRoute
  TeachersRoute: typeof TeachersRoute
  TimetablesRoute: typeof TimetablesRoute
  UsersRoute: typeof UsersRoute
  PlanningsPlanningIdRoute: typeof PlanningsPlanningIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timetables': {
      id: '/timetables'
      path: '/timetables'
      fullPath: '/timetables'
      preLoaderRoute: typeof TimetablesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teachers': {
      id: '/teachers'
      path: '/teachers'
      fullPath: '/teachers'
      preLoaderRoute: typeof TeachersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/students': {
      id: '/students'
      path: '/students'
      fullPath: '/students'
      preLoaderRoute: typeof StudentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rooms': {
      id: '/rooms'
      path: '/rooms'
      fullPath: '/rooms'
      preLoaderRoute: typeof RoomsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/departments': {
      id: '/departments'
      path: '/departments'
      fullPath: '/departments'
      preLoaderRoute: typeof DepartmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo-mode': {
      id: '/demo-mode'
      path: '/demo-mode'
      fullPath: '/demo-mode'
      preLoaderRoute: typeof DemoModeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classes': {
      id: '/classes'
      path: '/classes'
      fullPath: '/classes'
      preLoaderRoute: typeof ClassesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plannings/$planningId': {
      id: '/plannings/$planningId'
      path: '/plannings/$planningId'
      fullPath: '/plannings/$planningId'
      preLoaderRoute: typeof PlanningsPlanningIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClassesRoute: ClassesRoute,
  CoursesRoute: CoursesRoute,
  DemoModeRoute: DemoModeRoute,
  DepartmentsRoute: DepartmentsRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  RoomsRoute: RoomsRoute,
  SettingsRoute: SettingsRoute,
  StudentsRoute: StudentsRoute,
  TeachersRoute: TeachersRoute,
  TimetablesRoute: TimetablesRoute,
  UsersRoute: UsersRoute,
  PlanningsPlanningIdRoute: PlanningsPlanningIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
