// This file is auto-generated by TanStack Router
// Manually created for initial setup

import { RootRoute } from "@tanstack/react-router";
import { Route as rootRoute } from "./src/routes/__root";
import { Route as IndexRoute } from "./src/routes/index";
import { Route as LoginRoute } from "./src/routes/login";
import { Route as TeachersRoute } from "./src/routes/teachers";
import { Route as CoursesRoute } from "./src/routes/courses";
import { Route as RoomsRoute } from "./src/routes/rooms";
import { Route as DepartmentsRoute } from "./src/routes/departments";
import { Route as ClassesRoute } from "./src/routes/classes";
import { Route as TimetableRoute } from "./src/routes/plannings.$planningId";
import { Route as TimetablesRoute } from "./src/routes/timetables";
import { Route as TimetablesIdPlanningRoute } from "./src/routes/plannings.$planningId";
import { Route as ProfileRoute } from "./src/routes/profile";
import { Route as SettingsRoute } from "./src/routes/settings";
import { Route as UsersRoute } from "./src/routes/users";

const TimetablesRouteChildren = TimetablesRoute.addChildren([
  TimetablesIdPlanningRoute,
]);

const routeTree = rootRoute.addChildren([
  IndexRoute,
  LoginRoute,
  TeachersRoute,
  CoursesRoute,
  RoomsRoute,
  DepartmentsRoute,
  ClassesRoute,
  TimetableRoute,
  TimetablesRouteChildren,
  ProfileRoute,
  SettingsRoute,
  UsersRoute,
]);

export { routeTree };
